#pragma once
#include <string>

// ── Part 1: <!DOCTYPE>  through  <body> open  (before PIN) ───────
static const char REMOTE_HTML_PART1[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"bn\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\">\n"
    "<title>RasFocus Remote</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}\n"
    "body{font-family:'Segoe UI',sans-serif;background:#0d0d0d;color:#e0e0e0;height:100dvh;display:flex;flex-direction:column;overflow:hidden;user-select:none}\n"
    "#hdr{background:#005f6b;padding:8px 14px;display:flex;align-items:center;gap:8px;flex-shrink:0}\n"
    "#hdr h1{font-size:14px;font-weight:700;color:#fff;flex:1}\n"
    "#dot{width:10px;height:10px;border-radius:50%;background:#ff5252}\n"
    "#dot.on{background:#69f0ae;box-shadow:0 0 6px #69f0ae}\n"
    "#tabs{display:flex;background:#111;flex-shrink:0}\n"
    ".tab{flex:1;padding:10px 2px;text-align:center;font-size:11px;cursor:pointer;color:#666;border-bottom:2px solid transparent}\n"
    ".tab.active{color:#00bcd4;border-bottom-color:#00bcd4}\n"
    "#panels{flex:1;overflow:hidden;position:relative}\n"
    ".panel{display:none;position:absolute;inset:0;flex-direction:column}\n"
    ".panel.active{display:flex}\n"
    "#cout{flex:1;overflow-y:auto;background:#080808;font:12px/1.5 monospace;padding:8px;white-space:pre-wrap;word-break:break-all;color:#00e676}\n"
    "#cbar{display:flex;gap:6px;padding:7px;background:#181818;flex-shrink:0}\n"
    "#cin{flex:1;background:#111;border:1px solid #2a2a2a;color:#fff;padding:7px 9px;border-radius:6px;font-size:13px}\n"
    "#cbtn{background:#005f6b;color:#fff;border:none;padding:7px 14px;border-radius:6px;cursor:pointer;font-size:13px}\n"
    "#pbar{padding:7px 12px;background:#111;font-size:11px;color:#888;flex-shrink:0;word-break:break-all}\n"
    "#flist{flex:1;overflow-y:auto}\n"
    ".fi{display:flex;align-items:center;gap:10px;padding:10px 13px;border-bottom:1px solid #1a1a1a;cursor:pointer}\n"
    ".fi:active{background:#1e2e2e}\n"
    ".fic{font-size:19px;width:26px;text-align:center}\n"
    ".fin{font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    ".fsz{font-size:10px;color:#555;margin-top:1px}\n"
    "#fup{width:100%;padding:8px 13px;background:#1a1a1a;color:#00bcd4;border:none;font-size:12px;cursor:pointer;text-align:left;flex-shrink:0}\n"
    "#swrap{flex:1;display:flex;align-items:center;justify-content:center;background:#000;position:relative;overflow:hidden}\n"
    "#simg{max-width:100%;max-height:100%;object-fit:contain;display:block;touch-action:none}\n"
    "#sov{position:absolute;inset:0;touch-action:none}\n"
    "#sbar{display:flex;gap:5px;padding:7px;background:#181818;flex-shrink:0;align-items:center}\n"
    "#sbar label{font-size:11px;color:#666}\n"
    "#rbtn{background:#1e3a3a;color:#00bcd4;border:none;padding:5px 10px;border-radius:6px;font-size:11px;cursor:pointer;margin-left:auto}\n"
    "#ctbtn{background:#005f6b;color:#fff;border:none;padding:5px 10px;border-radius:6px;font-size:11px;cursor:pointer}\n"
    "#tbar{display:none;gap:5px;padding:7px;background:#111;flex-shrink:0}\n"
    "#tbar.show{display:flex}\n"
    "#tin{flex:1;background:#0d0d0d;border:1px solid #2a2a2a;color:#fff;padding:6px 9px;border-radius:6px;font-size:13px}\n"
    "#tsnd{background:#005f6b;color:#fff;border:none;padding:6px 11px;border-radius:6px;cursor:pointer}\n"
    "#keys{display:none;flex-wrap:wrap;gap:4px;padding:6px;background:#111;flex-shrink:0}\n"
    "#keys.show{display:flex}\n"
    ".key{background:#1e1e1e;color:#ccc;border:none;padding:6px 10px;border-radius:5px;font-size:12px;cursor:pointer}\n"
    ".key:active{background:#333}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"hdr\">\n"
    "  <span id=\"dot\"></span>\n"
    "  <h1>RasFocus Remote</h1>\n"
    "  <span style=\"font-size:11px;color:#7dffdd\">PIN: ";

// ── Part 2: after PIN  through  </html> ──────────────────────────
static const char REMOTE_HTML_PART2[] =
    "</span>\n"
    "</div>\n"
    "<div id=\"tabs\">\n"
    "  <div class=\"tab active\" onclick=\"swTab('cmd')\">CMD</div>\n"
    "  <div class=\"tab\" onclick=\"swTab('files')\">Files</div>\n"
    "  <div class=\"tab\" onclick=\"swTab('screen')\">Screen</div>\n"
    "</div>\n"
    "<div id=\"panels\">\n"
    "  <div class=\"panel active\" id=\"panel-cmd\">\n"
    "    <div id=\"cout\">Connecting...\n</div>\n"
    "    <div id=\"cbar\">\n"
    "      <input id=\"cin\" placeholder=\"command...\" onkeydown=\"if(event.key==='Enter')sc()\">\n"
    "      <button id=\"cbtn\" onclick=\"sc()\">Run</button>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"panel\" id=\"panel-files\">\n"
    "    <button id=\"fup\" onclick=\"gup()\">^ Up</button>\n"
    "    <div id=\"pbar\">C:\\</div>\n"
    "    <div id=\"flist\"></div>\n"
    "  </div>\n"
    "  <div class=\"panel\" id=\"panel-screen\">\n"
    "    <div id=\"sbar\">\n"
    "      <label>Live Screen</label>\n"
    "      <button id=\"rbtn\" onclick=\"rf()\">Refresh</button>\n"
    "      <button id=\"ctbtn\" onclick=\"tgCtrl()\">Control: OFF</button>\n"
    "    </div>\n"
    "    <div id=\"keys\">\n"
    "      <button class=\"key\" onclick=\"sk(27)\">Esc</button>\n"
    "      <button class=\"key\" onclick=\"sk(9)\">Tab</button>\n"
    "      <button class=\"key\" onclick=\"sk(13)\">Enter</button>\n"
    "      <button class=\"key\" onclick=\"sk(8)\">BkSp</button>\n"
    "      <button class=\"key\" onclick=\"sk(46)\">Del</button>\n"
    "      <button class=\"key\" onclick=\"sk(37)\">Left</button>\n"
    "      <button class=\"key\" onclick=\"sk(38)\">Up</button>\n"
    "      <button class=\"key\" onclick=\"sk(40)\">Down</button>\n"
    "      <button class=\"key\" onclick=\"sk(39)\">Right</button>\n"
    "      <button class=\"key\" onclick=\"sk(91)\">Win</button>\n"
    "      <button class=\"key\" onclick=\"sk(18)\">Alt</button>\n"
    "      <button class=\"key\" onclick=\"sk(17)\">Ctrl</button>\n"
    "    </div>\n"
    "    <div id=\"tbar\">\n"
    "      <input id=\"tin\" placeholder=\"Type...\">\n"
    "      <button id=\"tsnd\" onclick=\"stype()\">Send</button>\n"
    "    </div>\n"
    "    <div id=\"swrap\">\n"
    "      <img id=\"simg\" src=\"\" alt=\"\">\n"
    "      <div id=\"sov\"></div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<script>\n"
    "var ws,cp='C:\\\\',ctrl=false,live=false,lt=null;\n"
    "function conn(){\n"
    "  ws=new WebSocket('ws://'+location.host+'/ws');\n"
    "  ws.onopen=function(){document.getElementById('dot').className='on';\n"
    "    document.getElementById('cout').textContent='Connected!\\n';};\n"
    "  ws.onclose=function(){document.getElementById('dot').className='';\n"
    "    setTimeout(conn,2000);};\n"
    "  ws.onmessage=function(e){\n"
    "    var d=JSON.parse(e.data);\n"
    "    if(d.type==='shell_result'){var o=document.getElementById('cout');\n"
    "      o.textContent+=d.output+'\\n';o.scrollTop=o.scrollHeight;}\n"
    "    else if(d.type==='files_result'){rf2(d.path,d.items);}\n"
    "    else if(d.type==='screen_frame'){\n"
    "      document.getElementById('simg').src='data:image/jpeg;base64,'+d.jpeg;\n"
    "      if(live)lt=setTimeout(rf,400);}\n"
    "  };\n"
    "}\n"
    "function snd(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o));}\n"
    "function sc(){var i=document.getElementById('cin'),c=i.value.trim();\n"
    "  if(!c)return;var o=document.getElementById('cout');\n"
    "  o.textContent+='> '+c+'\\n';snd({type:'shell',cmd:c});i.value='';}\n"
    "function swTab(n){\n"
    "  var tabs=['cmd','files','screen'];\n"
    "  document.querySelectorAll('.tab').forEach(function(t,i){\n"
    "    t.classList.toggle('active',tabs[i]===n);});\n"
    "  document.querySelectorAll('.panel').forEach(function(p){\n"
    "    p.classList.toggle('active',p.id==='panel-'+n);});\n"
    "  if(n==='files')lf(cp);\n"
    "  if(n==='screen')rf();\n"
    "}\n"
    "function lf(p){cp=p;document.getElementById('pbar').textContent=p;\n"
    "  document.getElementById('flist').textContent='...';snd({type:'files',path:p});}\n"
    "function rf2(p,it){\n"
    "  cp=p;document.getElementById('pbar').textContent=p;\n"
    "  var el=document.getElementById('flist');el.innerHTML='';\n"
    "  it.forEach(function(f){\n"
    "    var d=document.createElement('div');d.className='fi';\n"
    "    d.innerHTML='<span class=\"fic\">'+(f.dir?'[D]':'[F]')+'</span>'\n"
    "      +'<div><div class=\"fin\">'+f.name+'</div>'\n"
    "      +'<div class=\"fsz\">'+(f.dir?'Folder':fsz(f.size))+'</div></div>';\n"
    "    if(f.dir)d.onclick=function(){lf(p+'\\\\'+f.name);};\n"
    "    el.appendChild(d);\n"
    "  });\n"
    "}\n"
    "function gup(){var parts=cp.split('\\\\').filter(Boolean);\n"
    "  if(parts.length<=1){lf('C:\\\\');return;}\n"
    "  parts.pop();lf(parts.join('\\\\')+(parts.length===1?'\\\\':''));}\n"
    "function fsz(n){if(n<1024)return n+'B';\n"
    "  if(n<1048576)return(n/1024).toFixed(1)+'KB';\n"
    "  return(n/1048576).toFixed(1)+'MB';}\n"
    "function rf(){clearTimeout(lt);snd({type:'screen'});}\n"
    "function tgCtrl(){\n"
    "  ctrl=!ctrl;\n"
    "  document.getElementById('ctbtn').textContent='Control: '+(ctrl?'ON':'OFF');\n"
    "  document.getElementById('ctbtn').style.background=ctrl?'#b71c1c':'#005f6b';\n"
    "  document.getElementById('tbar').className=ctrl?'show':'';\n"
    "  document.getElementById('keys').className=ctrl?'show':'';\n"
    "  live=ctrl;if(live)rf();else clearTimeout(lt);\n"
    "}\n"
    "function sk(vk){snd({type:'key',vk:vk});}\n"
    "function stype(){var i=document.getElementById('tin');\n"
    "  if(i.value){snd({type:'type',text:i.value});i.value='';}}\n"
    "var ov=document.getElementById('sov'),touching=false;\n"
    "function rel(e){var img=document.getElementById('simg'),\n"
    "  r=img.getBoundingClientRect(),\n"
    "  t=e.changedTouches?e.changedTouches[0]:e;\n"
    "  return{x:Math.max(0,Math.min(1,(t.clientX-r.left)/r.width)),\n"
    "         y:Math.max(0,Math.min(1,(t.clientY-r.top)/r.height))};}\n"
    "ov.addEventListener('touchstart',function(e){\n"
    "  if(!ctrl)return;e.preventDefault();var p=rel(e);\n"
    "  touching=true;snd({type:'mouse',x:p.x,y:p.y,btn:'left',act:'down'});},{passive:false});\n"
    "ov.addEventListener('touchend',function(e){\n"
    "  if(!ctrl)return;e.preventDefault();var p=rel(e);\n"
    "  touching=false;snd({type:'mouse',x:p.x,y:p.y,btn:'left',act:'up'});},{passive:false});\n"
    "ov.addEventListener('touchmove',function(e){\n"
    "  if(!ctrl)return;e.preventDefault();var p=rel(e);\n"
    "  snd({type:'mouse',x:p.x,y:p.y,btn:'left',act:'move'});},{passive:false});\n"
    "ov.addEventListener('dblclick',function(e){\n"
    "  if(!ctrl)return;var p=rel(e);\n"
    "  snd({type:'mouse',x:p.x,y:p.y,btn:'left',act:'dblclick'});});\n"
    "conn();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

// ── Helper ────────────────────────────────────────────────────────
static inline std::string BuildRemoteHtml(const std::string& pin) {
    return std::string(REMOTE_HTML_PART1) + pin + std::string(REMOTE_HTML_PART2);
}
